Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2022-12, with the labels that each got.

#569 first draft of Proof of Possession's documentation
  content/device-integration/mqtt-bundle/device-certificates.md
  static/images/mqtt/devmgmt-mqtt-cert-pop-check.png
  static/images/mqtt/devmgmt-mqtt-cert-pop-completed.png
  static/images/mqtt/devmgmt-mqtt-cert-pop-downloadunsigned.png
  static/images/mqtt/devmgmt-mqtt-cert-pop-uploadsigned.png
Labels: 10.15.0, 10.16.0

#690 [DM-1679]: Replaced images for data grid groups search and naming changes in wizard final step.
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devicecontrol-bulk-operation-wizard-step3.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devicecontrol-bulk-operation-wizard-step4.png
  static/images/users-guide/DeviceManagement/devmgmt-devicecontrol-bulk-operation-wizard-step3.png
  static/images/users-guide/DeviceManagement/devmgmt-devicecontrol-bulk-operation-wizard-step4.png
Labels: auto-backport, auto-backport-to-release/r10.16.0

#730 MTM-49961/MTM-47816 remove esper reference from microservice SDK…
  content/microservice-sdk/rest-bundle/microservice-development.md
Labels: 10.15.0, 10.16.0

#738 Removed the hyphen from the alarm text as discussed in review (PAB-3479)
  content/apama/troubleshooting-bundle/alarms.md
Labels: 10.17.0

#720 MTM-49965: reference-notifications: rework of non-persistent subscriptions and tokens
  content/reference/notifications-bundle/overview.md
Labels: auto-backport, auto-backport-to-release/r10.16.0

#732 modified spelling and max file size description.
  content/dtm/asset-types-bundle/property-library.md
Labels: 10.16.0

#740 Modified file upload part.
  content/dtm/asset-types-bundle/property-library.md
Labels: 10.16.0

#696 New "parent_tenant_not_subscribed" alarm (PAB-3532)
  content/apama/troubleshooting-bundle/alarms.md
Labels: 10.17.0

#714 [DM-1755] Add German screenshots for DM-164 for German User guide
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-bulk-registration.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-device-registration-tenant.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-device-registration.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-dropdown-menu.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-register-devices-custom.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-registration-general.png
  static/images/users-guide/DeviceManagement/devmgmt-device-registration-tenant.png
  static/images/users-guide/DeviceManagement/devmgmt-registration-general.png
Labels: 10.15.0, 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0
