Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2022-10, with the labels that each got.

#619 MTM-46186: Clarify messaging release support
  content/reference/notifications-bundle/overview.md
  content/users-guide/enterprise-tenant-bundle/ms-data-broker.md
Labels: 10.14.0

#624 PAB-3038: Document fully qualified names of events in Streaming Analytics guide
  content/apama/actions-bundle/invoking-http.md
  content/apama/actions-bundle/invoking-other-api.md
  content/apama/actions-bundle/querying.md
  content/apama/advanced-bundle/custom-fragments.md
  content/apama/advanced-bundle/measurement-fragments.md
  content/apama/analytics-introduction-bundle/events-and-channels.md
  content/apama/analytics-introduction-bundle/example.md
Labels: 10.16.0

#603 MTM-47846: doc: first cut of pulsar and databroker install guide
  content/edge/databroker-bundle/databroker-edge.md
  content/edge/databroker-bundle/index.html
  content/edge/databroker.md
Labels: 10.16.0

#634 [MTM-47904] New SSO access mapping configuration enabled
  content/users-guide/administration-bundle/changing-settings.md
  static/images/users-guide/Administration/sso-custom-access-mapping-2.png
  static/images/users-guide/Administration/sso-custom-access-mapping.png
Labels: 10.16.0

#632 Edge 109. Updated the migration procedure.
  content/edge/migration-bundle/before-you-begin.md
  content/edge/migration-bundle/creating-backup-on-107.md
  content/edge/migration-bundle/index.html
  content/edge/migration-bundle/migration-107-to-109.md
  content/edge/migration-bundle/restoring-the-data-on-edge-109.md
  content/edge/migration-bundle/sample-scripts-to-automate-the-migration.md
Labels: 10.9.0

#620 MTM-45961 Document how the knowledge hub from gainsight can be removed
  content/users-guide/getting-started-bundle/knowledge-hub.md
  static/images/users-guide/getting-started/getting-started-knowledge-hub-turning-off.png
Labels: 10.15.0

#635 MTM-48465 - documenation for tenant sso configuration access
  content/users-guide/administration-bundle/changing-settings.md
Labels: 10.16.0

#637 MTM-45799 add generic information about inventory roles improvements for 10.14
  content/users-guide/administration-bundle/managing-permissions.md
Labels: 10.14.0, 10.15.0

#545 DM-428 custom action jmx bean (without fork)
  content/protocol-integration/opcua-bundle/troubleshooting.md
  static/images/device-protocols/opcua/opcua-jmx-customActionMBean-CounterTable.png
  static/images/device-protocols/opcua/opcua-jmx-customActionMBean-RetryQueueSize.png
  static/images/device-protocols/opcua/opcua-jmx-mbeans.png
Labels: on hold

#636 MTM-45799 add generic information about inventory roles improvements …
  content/users-guide/administration-bundle/managing-permissions.md
Labels: 10.13.0

#628 MTM-45799 add generic information about inventory roles improvements
  content/users-guide/administration-bundle/managing-permissions.md
Labels: 10.16.0

#647 Add "com.apama.util" to AnyExtractor
  content/apama/actions-bundle/invoking-http.md
Labels: 10.16.0

#655 Updates to the Streaming Analytics guide after changing the 10.15 release notes
  content/apama/advanced-bundle/optimize-requests.md
Labels: 10.15.0, 10.16.0
