Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2022-05, with the labels that each got.

#329 Feature/MTM-38615 Microservice SDK guide update
  content/microservice-sdk/concept-bundle/manifest.md
  content/microservice-sdk/concept-bundle/microservice-runtime.md
  content/microservice-sdk/concept-bundle/migration.md
Labels: 10.14.0, on hold

#392 Changed shortcode for Analytics Builder doc to point to 10.14
  themes/c8ydocs/layouts/shortcodes/link-analytics-builder.html
Labels: 10.14.0

#369 DM-431 Add docker wait setting
  content/microservice-sdk/java-bundle/developing-microservice.md
Labels: 10.15.0
