Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2022-09, with the labels that each got.

#596 DM-1376: Shell tab screenshots modified
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devices-shell.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-shell.png
Labels: 10.15.0

#601 MTM-48016 add information about the restrictions on application-key
  content/concepts/applications-bundle/overview.md
  content/web/application-configuration-bundle/application-options.md
Labels: 10.13.0, 10.11.0, 10.10.0, 10.9.0, 10.14.0, 10.15.0, 10.16.0

#607 DM-1336 New connector operations
  content/protocol-integration/lwm2m-bundle/connector-device.md
Labels: 10.16.0

#606 feature/MTM-46136/MTM-46140-Add-requirements-for-managing-applications-and-microservices
  content/users-guide/administration-bundle/managing-applications.md
Labels: 10.16.0

#618 MTM-46186: Clarify messaging release support
  content/reference/notifications-bundle/overview.md
  content/users-guide/enterprise-tenant-bundle/ms-data-broker.md
Labels: 10.15.0

#622 MTM-46186: Clarify messaging release support
  content/reference/notifications-bundle/overview.md
  content/users-guide/enterprise-tenant-bundle/ms-data-broker.md
Labels: 10.11.0
