Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2022-08, with the labels that each got.

#489 DM-1109 Add documentation for image parameter of package plugin
  content/microservice-sdk/java-bundle/developing-microservice.md
Labels: on hold, 10.15.0

#539 Feature/data hub 10 15
  content/datahub/datahub-overview-bundle/datahub-at-a-glance.md
  content/datahub/datahub-overview-bundle/documentation-overview.md
  content/datahub/getting-started-with-datahub-bundle/accessing-and-logging-in.md
  content/datahub/getting-started-with-datahub-bundle/overview-of-ui-features.md
  content/datahub/getting-started-with-datahub-bundle/tenant-and-user-settings.md
  content/datahub/integrating-datahub-with-other-products-bundle/integration-powerbi.md
  content/datahub/operating-datahub-bundle/tracking-usage-statistics.md
  content/datahub/operating-datahub-bundle/viewing-audit-logs.md
  content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge.md
  content/datahub/setting-up-datahub-bundle/defining-permissions.md
  content/datahub/setting-up-datahub-bundle/prerequisites.md
  content/datahub/setting-up-datahub-bundle/setting-up-dremio-users.md
  content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
  content/datahub/working-with-datahub-bundle/configuring-offloading-jobs.md
  content/datahub/working-with-datahub-bundle/datahub-best-practices.md
  content/datahub/working-with-datahub-bundle/managing-offloading-jobs.md
  content/datahub/working-with-datahub-bundle/monitoring-compaction-jobs.md
  content/datahub/working-with-datahub-bundle/monitoring-offloading-jobs.md
  content/datahub/working-with-datahub-bundle/offloading-base-collections.md
  content/datahub/working-with-datahub-bundle/overview-offloading.md
  content/datahub/working-with-datahub-bundle/querying-offloaded.md
  content/datahub/working-with-datahub-bundle/refining-offloaded.md
  content/datahub/working-with-datahub.md
  static/images/datahub-guide/datahub-configure-addtl-cols.png
  static/images/datahub-guide/datahub-configure-offloading-tasks.png
  static/images/datahub-guide/datahub-define-an-offloading-task.png
  static/images/datahub-guide/datahub-home-page.png
  static/images/datahub-guide/datahub-validate-an-offloading-configuration.png
Labels: 10.15.0

#554 PAQ: Safe mode
  content/apama/troubleshooting-bundle/alarms.md
Labels: 10.15.0

#559 adding details of the application name
  content/microservice-sdk/concept-bundle/ms-utility-tool.md
Labels: 10.13.0, 10.14.0, 10.15.0

#568 PAB-3331: Change in Docker Hub URL
  content/apama/analytics-introduction-bundle/deploying-apps.md
Labels: 10.13.0, 10.11.0, 10.14.0, 10.15.0

#574 PAB-3323: Update links in C8Y doc to the new structure on the doc website
  content/apama/actions-bundle/invoking-other-api.md
  content/apama/actions-bundle/querying.md
  content/apama/actions-bundle/utility-functions.md
  content/apama/advanced-bundle/Listeners.md
  content/apama/advanced-bundle/measurement-fragments.md
  content/apama/advanced-bundle/optimize-requests.md
  content/apama/analytics-introduction-bundle/developing-apps.md
  content/apama/analytics-introduction-bundle/events-and-channels.md
  content/apama/analytics-introduction-bundle/testing-apps.md
  content/apama/troubleshooting-bundle/alarms.md
  content/benutzerhandbuch/cockpit-de-bundle/smart-rules-collection.md
  content/users-guide/cockpit-bundle/smart-rules-collection.md
  themes/c8ydocs/layouts/shortcodes/link-analytics-builder.html
  themes/c8ydocs/layouts/shortcodes/link-apama-webhelp.html
  themes/c8ydocs/layouts/shortcodes/link-apamadoc-api.html
Labels: 10.15.0

#576 PAM-33911: Multi-tenancy in streaming analytics
  content/apama/analytics-introduction-bundle/deploying-apps.md
  content/apama/analytics-introduction-bundle/developing-apps.md
  content/apama/microservices-bundle/connect.md
Labels: 10.15.0

#401 extensible device registration docs
  content/concepts/applications-bundle/extensible-device-registration.md
  content/users-guide/device-management-bundle/connecting-devices.md
  static/images/concepts-guide/extensible-device-registration/bulk-diagram-sync.png
  static/images/concepts-guide/extensible-device-registration/extensible-bulk-device-reg.png
  static/images/concepts-guide/extensible-device-registration/extensible-single-device-reg.png
  static/images/concepts-guide/extensible-device-registration/register-device-menu-with-extensible-device-reg.png
  static/images/concepts-guide/extensible-device-registration/single-diagram.png
Labels: 10.15.0

#473 Improvement/dtm guide
  content/dtm.md
  content/dtm/_index.html
  content/dtm/asset-hierarchy-bundle/creating-assets-bulk-import.md
  content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
  content/dtm/asset-hierarchy-bundle/index.html
  content/dtm/asset-hierarchy-bundle/viewing-assets.md
  content/dtm/asset-hierarchy.md
  content/dtm/asset-types-bundle/asset-types.md
  content/dtm/asset-types-bundle/index.html
  content/dtm/asset-types-bundle/property-library.md
  content/dtm/asset-types.md
  content/dtm/dtm-introduction.md
  content/dtm/localization.md
  content/users-guide/cockpit-bundle/data-explorer.md
  static/images/dtm/asset-type/dtm-asset-type-create-new-custom-property.png
  static/images/dtm/asset-type/dtm-asset-type-select-icon.png
  static/images/dtm/asset-type/dtm-asset-type-validation-error.png
  static/images/dtm/asset-type/dtm-asset-type-view.png
  static/images/dtm/assets/dtm-asset-type-create-new.png
  static/images/dtm/assets/dtm-assets-add-child-asset.png
  static/images/dtm/assets/dtm-assets-add-multiple-instance.png
  static/images/dtm/assets/dtm-assets-assign-devices.png
  static/images/dtm/assets/dtm-assets-confirmation-page.png
  static/images/dtm/assets/dtm-assets-create-date-type.png
  static/images/dtm/assets/dtm-assets-create-enum-type.png
  static/images/dtm/assets/dtm-assets-create-text-type.png
  static/images/dtm/assets/dtm-assets-no-assets.png
  static/images/dtm/assets/dtm-assets-subassets-page-details.png
  static/images/dtm/assets/dtm-assets-subassets-page.png
  static/images/dtm/assets/dtm-assets-view-assets.png
  static/images/dtm/bulk-import/dtm-bulk-import-add-permission.png
  static/images/dtm/bulk-import/dtm-bulk-import-assign-permissions.png
  static/images/dtm/bulk-import/dtm-bulk-import-failed-asset-imports.png
  static/images/dtm/bulk-import/dtm-bulk-import-import-assets-window.png
  static/images/dtm/bulk-import/dtm-bulk-import-template.png
  static/images/dtm/custom-property/dtm-property-library-complex-property.png
  static/images/dtm/custom-property/dtm-property-library-create-property.png
  static/images/dtm/custom-property/dtm-property-library-simple-custom-property.png
  static/images/dtm/custom-property/dtm-property-library-type-enum.png
  static/images/dtm/custom-property/dtm-property-library-type-text.png
  static/images/dtm/localization/dtm-localization-add-term.png
  static/images/dtm/localization/dtm-localozation-main-page.png
Labels: 10.15.0

#536 MTM-46296 update the docs with the info about mutlti-type filtering in notification2 subscriptions
  content/reference/notifications-bundle/overview.md
Labels: 10.16.0

#588 PAQ: Docker images as of Apama 10.15
  content/apama/analytics-introduction-bundle/deploying-apps.md
Labels: 10.15.0

#587 removed a versioned link to the datahub openapi documentation
  content/datahub/working-with-datahub-bundle/querying-offloaded.md
Labels: 10.14.0, 10.15.0

#584 [DM-1386]: Removed references to bulk operation tab in groups which i…
  content/users-guide/device-management-bundle/managing-device-data.md
  content/users-guide/device-management-bundle/monitoring-and-controlling-devices.md
Labels: 10.15.0

#579 [DM-1383]: Fixed outdated text and screenshots in grouping devices.
  content/users-guide/cockpit-bundle/managing-assets.md
  content/users-guide/device-management-bundle/grouping-devices.md
  content/users-guide/getting-started-bundle/gui-features.md
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-group-assign.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-group-details.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-group-filter.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-groups-smartgroups-filter.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-groups.png
  static/images/users-guide/DeviceManagement/devmgmt-group-assign.png
  static/images/users-guide/DeviceManagement/devmgmt-group-details.png
  static/images/users-guide/DeviceManagement/devmgmt-group-filter.png
  static/images/users-guide/DeviceManagement/devmgmt-groups-smartgroups-filter.png
  static/images/users-guide/DeviceManagement/devmgmt-groups.png
Labels: 10.15.0

#573 Feature/DM-1382 reviewing viewing devices 10.15.0
  content/benutzerhandbuch/device-management-de-bundle/overview.md
  content/benutzerhandbuch/device-management-de-bundle/viewing-devices.md
  content/edge/edge-introduction-bundle/iot-platform.md
  content/users-guide/device-management-bundle/overview.md
  content/users-guide/device-management-bundle/viewing-devices.md
  static/images/users-guide/DeviceManagement/devmgmt-devices-alldevices.png
Labels: 10.15.0

#575 DM-1394: changed all different spellings and versions of device exter…
  content/reference/device-management-library-bundle/configuration.md
  content/reference/device-management-library-bundle/firmware.md
  content/reference/device-management-library-bundle/software.md
Labels: 10.15.0

#589 DM-1391 device integration using rest review
  content/device-sdk/device-sdk-rest-bundle/device-integration.md
  content/device-sdk/device-sdk-rest-bundle/hello-rest.md
  content/device-sdk/device-sdk-rest-bundle/overview.md
Labels: 10.15.0

#585 DM-1421: Updated device details page
  content/benutzerhandbuch/device-management-de-bundle/device-details.md
  content/users-guide/device-management-bundle/device-details.md
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devices-control.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devices-measurements.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devices-shell-precommands.png
  static/images/benutzerhandbuch/DeviceManagement/devmgmt-devices-shell.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-control.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-measurements.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-shell-precommands.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-shell.png
Labels: 10.15.0
