Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2022-11, with the labels that each got.

#648 bugherd task #524
  content/device-sdk/device-sdk-rest-bundle/device-integration.md
  content/device-sdk/device-sdk-rest-bundle/hello-rest.md
  content/device-sdk/device-sdk-rest-bundle/overview.md
Labels: 10.13.0, 10.11.0, 10.14.0

#658 PAQ: High memory usage (PAB-3477)
  content/apama/troubleshooting-bundle/alarms.md
Labels: 10.13.0, 10.11.0, 10.14.0, 10.15.0, 10.16.0, 10.17.0

#662 Shortcodes: Update PAM and PAB links for 10.16
  themes/c8ydocs/layouts/shortcodes/link-analytics-builder.html
  themes/c8ydocs/layouts/shortcodes/link-apama-webhelp.html
  themes/c8ydocs/layouts/shortcodes/link-apamadoc-api.html
Labels: 10.16.0

#663 test change for auto cherry-pick
  README.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0

#665 Documentation changes for 10.16
  content/dtm/asset-hierarchy-bundle/creating-assets-bulk-import.md
  content/dtm/asset-hierarchy-bundle/viewing-assets.md
  content/dtm/asset-types-bundle/asset-types.md
  content/dtm/asset-types-bundle/property-library.md
Labels: 10.16.0

#684 Documentation changes for 10.16 into respective branch
  content/dtm/asset-hierarchy-bundle/creating-assets-bulk-import.md
  content/dtm/asset-hierarchy-bundle/viewing-assets.md
  content/dtm/asset-types-bundle/asset-types.md
  content/dtm/asset-types-bundle/property-library.md
Labels: 10.16.0

#681 PAB-3484: Replace application_queue_full alarm with 3 new ones
  content/apama/troubleshooting-bundle/alarms.md
Labels: 10.17.0
