Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-12, with the labels that each got.

#1582 bugherd task 762
  content/device-integration/device-integration-introduction.md
Labels: 10.18.0

#1571 deprecation banner for 1014 and earlier
  themes/c8ydocs/static/js/main.js
Labels: 10.13.0, 10.11.0, 10.10.0, 10.14.0, auto-backport, auto-backport-to-release/r10.13.0, auto-backport-to-release/r10.11.0, auto-backport-to-release/r10.10.0

#1585 MTM-55819 changing TS parameters description to clear inconsistency
  content/users-guide/enterprise-tenant-bundle/timeseries.md
Labels: 10.16.0, 10.17.0

#1566 DTM 1019.1.0 - Asset Location, Ordering of complex properties documentation
  content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
  content/dtm/asset-hierarchy-bundle/viewing-assets.md
  content/dtm/asset-types-bundle/asset-properties.md
  static/images/dtm/custom-property/dtm-property-library-complex-property.png
Labels: not-yet-deployed, DTM

#1551 DTM 1019.1.0 user guide
  content/dtm/asset-types-bundle/asset-properties.md
  content/dtm/localization.md
  static/images/dtm/localization/dtm-localization-add-term.png
  static/images/dtm/localization/dtm-localization-main-page.png
Labels: DTM

#1540 DTM 1019.1.0 change log
  content/changes-applications/cl-dtm.md
Labels: DTM

#1579 bugherd task 759 - section restored for 1018
  content/device-integration/mqtt-bundle/device-certificates.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.13.0, auto-backport-to-release/r10.17.0, 10.18.0, auto-backport-to-release/r10.11.0

#1534 Bugfix/MTM-53267_extending_user_context_description
  content/microservice-sdk/java-bundle/developing-microservice.md
Labels: Draft
