Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-07, with the labels that each got.

#1201 Automated Handover: 10.18.1 Analytics Builder Block Reference Documentation.
  content/streaming-analytics/block-reference-bundle/calculation.md
Labels: 10.19.0

#1214 [no-issue] initial pr pipeline
  .github/workflows/pull-request.yml
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.13.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1230 [no-issue] deploy built docs to surge for preview
  .github/workflows/pull-request.yml
  themes/c8ydocs/static/js/main.js
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.13.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1193 DM-2434 Updated "How does the platform support developing agents?" section.
  content/concepts/interfacing-devices-bundle/developing-agents.md
Labels: 10.19.0

#1251 [DM-2547]: Additional information for repository items not matching any device types added.
  content/users-guide/device-management-bundle/managing-device-data.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1259 PAB-4195: Change info on EPL memory profiler
  content/streaming-analytics/troubleshooting-bundle/alarms.md
  content/streaming-analytics/troubleshooting-bundle/diagnostics-download.md
Labels: 10.19.0
