Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-03, with the labels that each got.

#923 Update user-settings.md
  content/users-guide/getting-started-bundle/user-settings.md
Labels: 10.17.0

#826 DM-1821 SmartRest static templates 123 and 124.
  content/reference/smartrest-two-bundle/mqtt-static-templates.md
Labels: 10.18.0

#936 DM-2055: Removed the cluster tenant cleanup operation
  content/protocol-integration/lwm2m-bundle/connector-device.md
Labels: 10.18.0

#937 [MTM-47773] Misleading device availability documentation
  content/users-guide/device-management-bundle/monitoring-and-controlling-devices.md
Labels: 10.18.0

#824 DM-1832 MQTT Static templates 504, 505, 506 (updating operation by id).
  content/reference/smartrest-two-bundle/mqtt-static-templates.md
Labels: on hold, 10.18.0

#538 Administration related topics
  content/users-guide/administration-bundle/audit-logs.md
  content/users-guide/administration-bundle/business-rules.md
  content/users-guide/administration-bundle/changing-settings.md
  content/users-guide/administration-bundle/configuring-single-sign-on.md
  content/users-guide/administration-bundle/data-retention.md
  content/users-guide/administration-bundle/managing-applications.md
  content/users-guide/administration-bundle/managing-microservices.md
  content/users-guide/administration-bundle/managing-permissions.md
  content/users-guide/administration-bundle/managing-users.md
  content/users-guide/administration-bundle/tfa.md
Labels: 10.18.0

#613 MTM-44126 Added related topics to Getting started
  content/users-guide/getting-started-bundle/accessing-platform.md
  content/users-guide/getting-started-bundle/gui-features.md
  content/users-guide/getting-started-bundle/platform-applications.md
Labels: 10.18.0

#594 MTM-44129 Added related topics to Cockpit section
  content/users-guide/cockpit-bundle/dashboards.md
  content/users-guide/cockpit-bundle/data-explorer.md
  content/users-guide/cockpit-bundle/exports.md
  content/users-guide/cockpit-bundle/managing-assets.md
  content/users-guide/cockpit-bundle/overview.md
  content/users-guide/cockpit-bundle/reports.md
  content/users-guide/cockpit-bundle/smart-rules-collection.md
  content/users-guide/cockpit-bundle/smart-rules.md
  content/users-guide/cockpit-bundle/widgets-collection.md
Labels: 10.18.0

#825 DM-1820 SmartREST static template 143.
  content/reference/smartrest-two-bundle/mqtt-static-templates.md
Labels: on hold

#945 OPC UA Gateway thin-edge.io integration
  content/protocol-integration/opcua-bundle/gateway-register.md
  content/protocol-integration/opcua-bundle/register-gateway-as-device.md
Labels: 10.18.0

#955 [DM-2164] Home Page rev2 doc update
  content/users-guide/device-management-bundle/overview.md
  static/images/users-guide/DeviceManagement/device-management-home-screen.png
Labels: 10.18.0
