Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-05, with the labels that each got.

#1017 MTM-53068 improvements and refresh in microservice sdk docs.
  content/microservice-sdk/concept-bundle/security.md
  content/microservice-sdk/java-bundle/developing-microservice.md
  content/microservice-sdk/rest-bundle/microservice-development.md
Labels: 10.16.0, 10.17.0, 10.18.0

#1027 MTM-51481 added information about contextPath, updated to 10.16
  content/web/microfrontends-bundle/add-a-custom-widget-with-plugin.md
  content/web/microfrontends-bundle/add-a-new-package-as-blueprint.md
Labels: 10.16.0, 10.17.0, 10.18.0, 10.19.0

#1030 feature/MTM-50214/MTM-53144-documentation-improvements
  content/users-guide/administration-bundle/managing-permissions.md
  content/users-guide/administration-bundle/managing-users.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1050 Streaming Analytics : Update Analytics Builder block reference
  content/streaming-analytics/block-reference-bundle/aggregate.md
  content/streaming-analytics/block-reference-bundle/calculation.md
  content/streaming-analytics/block-reference-bundle/flow-manipulation.md
  content/streaming-analytics/block-reference-bundle/input.md
  content/streaming-analytics/block-reference-bundle/logic.md
  content/streaming-analytics/block-reference-bundle/output.md
  content/streaming-analytics/block-reference-bundle/overview-of-all-blocks.md
  content/streaming-analytics/block-reference-bundle/utility.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1031 feature/MTM-50214/MTM-53145-documentation-improvements
  content/users-guide/administration-bundle/managing-permissions.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1016 MTM-42115-Treatment-of-Unicode-word-characters-in-passwords
  content/users-guide/getting-started-bundle/user-settings.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1051 PAB-4030: Update info under "Restrictions for output blocks"
  content/streaming-analytics/analytics-builder-bundle/wires-and-blocks.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1060 PAQ: Move block reference up in ToC
  content/streaming-analytics/block-reference.md
  content/streaming-analytics/customization.md
  content/streaming-analytics/epl-apps.md
  content/streaming-analytics/troubleshooting.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1056 fix for missing image
  content/protocol-integration/lora-actility-bundle/troubleshooting.md
  static/images/device-protocols/lora-actility/lora-connectivity-invalid-credentials.png
Labels: 10.16.0

#1036 MTM-50640/MTM-53150-documentation-improvements
  content/users-guide/administration-bundle/managing-applications.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1020 MTM-53143-fixing-issues-reported-by-qa
  static/images/users-guide/Administration/admin-settings-properties-library.png
  themes/c8ydocs/assets/scss/_layout.scss
  themes/c8ydocs/assets/scss/_main-content.scss
  themes/c8ydocs/assets/scss/_main-top-bar.scss
  themes/c8ydocs/layouts/_default/bundle.html
  themes/c8ydocs/static/js/main.js
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1072 PAB-3974: Fixed the "/apama/" links to the restructured Streaming Analytics guide
  content/concepts/glossary.md
  content/concepts/realtime-bundle/realtime-processing-in-cumulocity.md
  content/edge/installation-bundle/accessing-platform.md
  content/machine-learning/activity-recognition-bundle/activity-recognition-using-demo-device.md
  content/machine-learning/activity-recognition-bundle/activity-recognition-using-iphone.md
  content/machine-learning/anomaly-detection-bundle/anomaly-detection-using-demo-device.md
  content/machine-learning/anomaly-detection-bundle/anomaly-detection-using-smartphone.md
  content/machine-learning/machine-learning-introduction-bundle/mle-overview.md
  content/users-guide/administration-bundle/managing-applications.md
  content/users-guide/administration-bundle/managing-microservices.md
  content/users-guide/cockpit-bundle/exports.md
  content/users-guide/cockpit-bundle/smart-rules-collection.md
  content/users-guide/getting-started-bundle/accessing-platform.md
  content/welcome/developers.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1068 Updates microservices.md to replace use of Zementis as the example
  content/streaming-analytics/epl-apps-bundle/microservices.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1035 [MTM-46148]-DOC-BD-UI-Add-requirements-for-account-settings
  content/users-guide/administration-bundle/changing-settings.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#996 MTM-43779 added audit records types to users guide
  content/users-guide/administration-bundle/audit-logs.md
Labels: 10.14.0, 10.15.0, 10.16.0, 10.17.0, 10.18.0, 10.19.0

#1015 [MTM-48946] Added a best practices section for micro frontends
  content/web/microfrontends-bundle/best-practices-for-packages.md
  content/web/microfrontends-bundle/index.html
  themes/c8ydocs/layouts/shortcodes/link-sag-community-plugins.html
Labels: 10.18.0, 10.19.0

#1042 [MTM-46145]-DOC-Add-requirements-for-managing-business-rules
  content/users-guide/administration-bundle/business-rules.md
  content/users-guide/administration-bundle/managing-applications.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1076 PAB-3836: Renaming of Use button
  content/streaming-analytics/analytics-builder-bundle/getting-started.md
  content/streaming-analytics/analytics-builder-bundle/using-the-instance-editor.md
  content/streaming-analytics/analytics-builder-bundle/using-the-model-editor.md
  content/streaming-analytics/analytics-builder-bundle/using-the-model-manager.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0

#1110 [MTM-57155] Added info about widget preview image size
  content/web/microfrontends-bundle/best-practices-for-packages.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1122 MTM-52868 Added information on versioningMatrix for packages.
  content/web/microfrontends-bundle/add-a-custom-widget-with-plugin.md
  content/web/microfrontends-bundle/add-a-new-package-as-blueprint.md
Labels: 10.19.0

#1034 MTM-51853 open ssl command to encrypt verification code
  content/device-integration/mqtt-bundle/device-certificates.md
Labels: 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1128 Copied over some important files from the DITA repo that are required…
  static/files/streaming-analytics/AnaBui-value-types-examples-source.xlsx
  static/files/streaming-analytics/AnaBui-value-types-screenshot-sources.xlsx
  static/files/streaming-analytics/images-for-model-execution-and-broadcast-devices.pptm
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#546 MTM-44133 related topics for device management
  content/users-guide/device-management-bundle/connecting-devices.md
  content/users-guide/device-management-bundle/connectivity.md
  content/users-guide/device-management-bundle/device-details.md
  content/users-guide/device-management-bundle/grouping-devices.md
  content/users-guide/device-management-bundle/managing-device-data.md
  content/users-guide/device-management-bundle/managing-device-types.md
  content/users-guide/device-management-bundle/monitoring-and-controlling-devices.md
  content/users-guide/device-management-bundle/monitoring-device-services.md
  content/users-guide/device-management-bundle/smartrest-templates.md
  content/users-guide/device-management-bundle/viewing-devices.md
Labels: on hold, 10.18.0
