Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-02, with the labels that each got.

#830 Updates for new Apama-ctrl-mt-4c-16g microservice (PAB-3422)
  content/apama/advanced-bundle/control-access.md
  content/apama/overview-analytics-bundle/microservice-and-applications.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#836 PAQ 10.17: Changed screenshots to show the new user menu
  static/images/apama/apama-epl-apps-cards.png
  static/images/apama/apama-epl-apps-editor.png
  static/images/apama/streaming-analytics-home-screen.png
Labels: 10.17.0, auto-backport-to-release/r10.17.0

#841 Update the default Apama microservices in the User guide
  content/users-guide/administration-bundle/managing-microservices.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#835 DM-1978: Replaced screenshots for Opcua Protocol Integration, removed…
  content/protocol-integration/opcua-bundle/authentication.md
  static/images/device-protocols/opcua/opcua-add-protocol.png
  static/images/device-protocols/opcua/opcua-address.png
  static/images/device-protocols/opcua/opcua-alarms.png
  static/images/device-protocols/opcua/opcua-auto-constraints.png
  static/images/device-protocols/opcua/opcua-data-reporting-subscription.png
  static/images/device-protocols/opcua/opcua-device-details.png
  static/images/device-protocols/opcua/opcua-device-protocol-applied.png
  static/images/device-protocols/opcua/opcua-device-protocol-unapplied.png
  static/images/device-protocols/opcua/opcua-device-protocol.png
  static/images/device-protocols/opcua/opcua-device-registration-gateway.png
  static/images/device-protocols/opcua/opcua-device-registration.png
  static/images/device-protocols/opcua/opcua-events.png
  static/images/device-protocols/opcua/opcua-gateway-memory.png
  static/images/device-protocols/opcua/opcua-keystore-explorer1.png
  static/images/device-protocols/opcua/opcua-keystore-explorer2.png
  static/images/device-protocols/opcua/opcua-keystore.png
  static/images/device-protocols/opcua/opcua-new-server.png
  static/images/device-protocols/opcua/opcua-server-child-device.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#857 Revert "DM-2000: Skip nodes without defined namespace"
  content/protocol-integration/opcua-bundle/authentication.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#804 Feature/mtm 50973 updated outdated info
  content/web/tutorials-bundle/add-a-custom-widget.md
  content/web/tutorials-bundle/add-a-tab-to-a-device.md
  content/web/tutorials-bundle/add-a-unit-test.md
  content/web/tutorials-bundle/extend-an-existing-application.md
  content/web/tutorials-bundle/remove-login-and-authentication.md
  content/web/tutorials-bundle/requesting-data-from-a-custom-microservice.md
  static/images/web-sdk/cockpit-dashboard-widgets.png
  static/images/web-sdk/custom-client-service.png
  static/images/web-sdk/custom-widget.png
  static/images/web-sdk/device-detail-custom-tab.png
  static/images/web-sdk/route-extension-hook.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#868 DM-1818 OPC UA: Add missing documentation for device type endpoints
  content/protocol-integration/opcua-bundle/rest-api.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#858 [MTM-50749] Updated screenshots for Web SDK - Getting started
  content/web/gettingstarted.md
  static/images/web-sdk/hello-world-example.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#863 [MTM-50749] Updated screenshots for Web SDK: Tutorials
  content/web/tutorials-bundle/add-a-custom-widget.md
  content/web/tutorials-bundle/add-a-tab-to-a-device.md
  content/web/tutorials-bundle/extend-an-existing-application.md
  content/web/tutorials-bundle/requesting-data-from-a-custom-microservice.md
  static/images/web-sdk/custom-client-service.png
  static/images/web-sdk/custom-widget.png
  static/images/web-sdk/device-detail-custom-tab.png
  static/images/web-sdk/route-extension-hook.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#875 DM-1819 Fix configuration file in Docs
  content/protocol-integration/opcua-bundle/gateway-register.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#862 [MTM-50749] Updated screenshots for Web SDK: Micro frontends
  content/web/microfrontends-bundle/add-a-custom-widget-with-plugin.md
  content/web/microfrontends-bundle/add-a-new-package-as-blueprint.md
  static/images/web-sdk/module-federation-widget-plugin.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#883 MTM-50748 Change screenshots for Microservice SDK for Java
  static/images/microservices-sdk/ms-tracking-map.png
  static/images/microservices-sdk/ms-tracking-newdevice.png
Labels: auto-backport, auto-backport-to-release/r10.17.0

#866 DM-2000: Different wording
  content/protocol-integration/opcua-bundle/authentication.md
Labels: 10.18.0

#859 DM-1978:Changed Updated OPCUA screenshots as per reviews
  static/images/device-protocols/opcua/opcua-auto-constraints.png
  static/images/device-protocols/opcua/opcua-data-reporting-subscription.png
  static/images/device-protocols/opcua/opcua-device-protocol-applied.png
  static/images/device-protocols/opcua/opcua-new-server.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#877 DM-129 Add Subscription Update Interval / Remove refresh interval
  content/protocol-integration/opcua-bundle/gateway-register.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#884 DM-1619 add delimiter info for csv files
  content/benutzerhandbuch/device-management-de-bundle/connecting-devices.md
  content/users-guide/device-management-bundle/connecting-devices.md
Labels: 10.15.0, 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0

#892 [MTM-51449][DE] Remaining-screenshots-to-take-care-of
  static/images/benutzerhandbuch/Administration/admin-application-packages-info.png
  static/images/benutzerhandbuch/Administration/admin-application-packages-versions.png
  static/images/benutzerhandbuch/Administration/admin-application-packages.png
  static/images/benutzerhandbuch/Administration/admin-application-plugins-grid.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#888 [DM-2032] Remove identifiable names from screenshots
  content/reference/device-management-library-bundle/device-info.md
  static/images/reference-guide/device-details.png
  static/images/reference-guide/device-status.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#869 DM-1013 Fix properties in OPC UA failure handling
  content/protocol-integration/opcua-bundle/device-protocols.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#878 [DM-1989] [DOC] Add availability and prerequisites of LWM2M
  content/protocol-integration/lwm2m-bundle/overview.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#874 10.16.0 German translation user guide
  content/benutzerhandbuch/administration-de-bundle/audit-logs.md
  content/benutzerhandbuch/administration-de-bundle/changing-settings.md
  content/benutzerhandbuch/administration-de-bundle/configuring-single-sign-on.md
  content/benutzerhandbuch/administration-de-bundle/data-retention.md
  content/benutzerhandbuch/administration-de-bundle/home-screen.md
  content/benutzerhandbuch/administration-de-bundle/managing-applications.md
  content/benutzerhandbuch/administration-de-bundle/managing-microservices.md
  content/benutzerhandbuch/administration-de-bundle/managing-permissions.md
  content/benutzerhandbuch/administration-de-bundle/managing-users.md
  content/benutzerhandbuch/administration-de-bundle/overview.md
  content/benutzerhandbuch/administration-de-bundle/platform-configuration-settings.md
  content/benutzerhandbuch/administration-de-bundle/tfa.md
  content/benutzerhandbuch/cockpit-de-bundle/configuration.md
  content/benutzerhandbuch/cockpit-de-bundle/dashboards.md
  content/benutzerhandbuch/cockpit-de-bundle/data-explorer.md
  content/benutzerhandbuch/cockpit-de-bundle/exports.md
  content/benutzerhandbuch/cockpit-de-bundle/managing-assets.md
  content/benutzerhandbuch/cockpit-de-bundle/overview.md
  content/benutzerhandbuch/cockpit-de-bundle/reports.md
  content/benutzerhandbuch/cockpit-de-bundle/smart-rules-collection.md
  content/benutzerhandbuch/cockpit-de-bundle/smart-rules.md
  content/benutzerhandbuch/cockpit-de-bundle/using-widgets.md
  content/benutzerhandbuch/cockpit-de-bundle/widgets-collection.md
  content/benutzerhandbuch/device-management-de-bundle/connecting-devices.md
  content/benutzerhandbuch/device-management-de-bundle/connectivity.md
  content/benutzerhandbuch/device-management-de-bundle/device-details.md
  content/benutzerhandbuch/device-management-de-bundle/grouping-devices.md
  content/benutzerhandbuch/device-management-de-bundle/managing-device-data.md
  content/benutzerhandbuch/device-management-de-bundle/managing-device-types.md
  content/benutzerhandbuch/device-management-de-bundle/monitoring-and-controlling-devices.md
  content/benutzerhandbuch/device-management-de-bundle/viewing-devices.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/customization.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/data-broker.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/license-management.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/managing-tenants.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/ms-data-broker.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/overview.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/storage-quota.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/support-user-access.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/usage-and-billing.md
  content/benutzerhandbuch/enterprise-tenant-de-bundle/user-hierarchies.md
  content/benutzerhandbuch/getting-started-de-bundle/accessing-platform.md
  content/benutzerhandbuch/getting-started-de-bundle/gui-features.md
  content/benutzerhandbuch/getting-started-de-bundle/platform-applications.md
  content/benutzerhandbuch/getting-started-de-bundle/user-settings.md
  content/benutzerhandbuch/webMethods.md
Labels: 10.16.0

#904 PAB-3674: Remove ROLE_APPLICATION_MANAGEMENT_ADMIN and ROLE_OPTION_MANAGEMENT_ADMIN
  content/apama/advanced-bundle/microservice-permissions.md
Labels: 10.13.0, 10.14.0, 10.15.0, 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.13.0, auto-backport-to-release/r10.17.0, 10.18.0

#917 PAB-3674 - Be more explicit about the dangers of CEP admin permissions
  content/apama/analytics-introduction-bundle/developing-apps.md
Labels: 10.15.0, 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0, 10.18.0

#828 [DM-1977] Update screenshots in Protocol Integration: LWM2M
  content/protocol-integration/lwm2m-bundle/device-details.md
  content/protocol-integration/lwm2m-bundle/device-protocols.md
  content/protocol-integration/lwm2m-bundle/firmware-update.md
  content/protocol-integration/lwm2m-bundle/register-device.md
  content/protocol-integration/lwm2m-bundle/shell-commands.md
  content/protocol-integration/lwm2m-bundle/validation-rules.md
  static/images/device-protocols/lwm2m/lwm2m-add-new-firmware.png
  static/images/device-protocols/lwm2m/lwm2m-autoobserve.png
  static/images/device-protocols/lwm2m/lwm2m-connector-device-bulk-device-reg-res.png
  static/images/device-protocols/lwm2m/lwm2m-custom-action-connectivity-signal.png
  static/images/device-protocols/lwm2m/lwm2m-customactions.png
  static/images/device-protocols/lwm2m/lwm2m-device-reg-bulk-dialog-result-message.png
  static/images/device-protocols/lwm2m/lwm2m-deviceprotocol.png
  static/images/device-protocols/lwm2m/lwm2m-devices-audit.png
  static/images/device-protocols/lwm2m/lwm2m-devices-bootstrap.png
  static/images/device-protocols/lwm2m/lwm2m-devices-execute.png
  static/images/device-protocols/lwm2m/lwm2m-devices-operations.png
  static/images/device-protocols/lwm2m/lwm2m-devices-operations2.png
  static/images/device-protocols/lwm2m/lwm2m-devices-readinstance.png
  static/images/device-protocols/lwm2m/lwm2m-devices-readobject.png
  static/images/device-protocols/lwm2m/lwm2m-devices-sync.png
  static/images/device-protocols/lwm2m/lwm2m-devices-tooltip.png
  static/images/device-protocols/lwm2m/lwm2m-functionalities.png
  static/images/device-protocols/lwm2m/lwm2m-mapping-failure-alarms.png
  static/images/device-protocols/lwm2m/lwm2m-objects.png
  static/images/device-protocols/lwm2m/lwm2m-post-operations.png
  static/images/device-protocols/lwm2m/lwm2m-predefined-custom-actions.png
  static/images/device-protocols/lwm2m/lwm2m-protocol-example.png
  static/images/device-protocols/lwm2m/lwm2m-protocols-addrule.png
  static/images/device-protocols/lwm2m/lwm2m-protocols-example-validation.png
  static/images/device-protocols/lwm2m/lwm2m-protocols-removerule.png
  static/images/device-protocols/lwm2m/lwm2m-protocols-rules.png
  static/images/device-protocols/lwm2m/lwm2m-temperature-example.png
  static/images/device-protocols/lwm2m/lwm2m-tooltip-help-icon.png
  static/images/device-protocols/lwm2m/lwm2m-trigger-fota.png
  static/images/device-protocols/lwm2m/lwm2m-uploadDDF.png
  static/images/device-protocols/lwm2m/lwm2m-uploadprotocol.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0

#924 Revert "PAB-3674: Remove ROLE_APPLICATION_MANAGEMENT_ADMIN and ROLE_OPTION_MANAGEMENT_ADMIN "
  content/apama/advanced-bundle/microservice-permissions.md
Labels: 10.13.0, 10.14.0, 10.15.0, 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.13.0, auto-backport-to-release/r10.17.0, 10.18.0
