Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-06, with the labels that each got.

#1143 PAB-4074: Change alarm text for infinite loops
  content/streaming-analytics/troubleshooting-bundle/alarms.md
Labels: 10.19.0

#1033 MTM-51852 new screenshots for POP
  static/images/mqtt/mqtt-cert-check.png
  static/images/mqtt/mqtt-cert-download-unsigned.png
  static/images/mqtt/mqtt-cert-upload-signed.png
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1148 PAQ: Merge first two topics of the overview
  content/streaming-analytics/overview-streaming-analytics-bundle/analytics-builder.md
  content/streaming-analytics/overview-streaming-analytics-bundle/epl-apps.md
  content/streaming-analytics/overview-streaming-analytics-bundle/streaming-analytics-and-c8y.md
  content/streaming-analytics/overview-streaming-analytics-bundle/streaming-analytics.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1146 Consistent wording/markup for active/inactive state of Analytics Builder models
  content/streaming-analytics/analytics-builder-bundle/monitoring-and-configuration.md
  content/streaming-analytics/analytics-builder-bundle/using-the-model-editor.md
  content/streaming-analytics/analytics-builder-bundle/using-the-model-manager.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1159 Streaming Analytics: 10.18.1 Analytics Builder block reference documentation
  content/streaming-analytics/block-reference-bundle/calculation.md
  content/streaming-analytics/block-reference-bundle/input.md
  content/streaming-analytics/block-reference-bundle/overview-of-all-blocks.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1160 PAQ: Add link to audit logs
  content/streaming-analytics/troubleshooting-bundle/alarms.md
Labels: auto-backport, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1171 [MTM-53617] fixing help content link for extensions
  content/users-guide/administration-bundle/managing-applications.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1176 [MTM-54103] document pick from existing data point option
  content/users-guide/cockpit-bundle/data-point-library.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0
