Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-09, with the labels that each got.

#1386 MTM-55111 remove misleading statement about clean session which should be always set to true
  content/device-integration/mqtt-bundle/implementation.md
Labels: 10.15.0, 10.16.0, 10.17.0, 10.18.0

#1416 [MTM-55504][1018] add entry about custom web sdk registry
  content/web/development-tools-bundle/c8y-cli.md
  content/web/libraries.md
  content/web/tutorials-bundle/add-a-custom-widget.md
  content/web/tutorials-bundle/add-a-tab-to-a-device.md
  content/web/tutorials-bundle/add-a-unit-test.md
  content/web/tutorials-bundle/extend-an-existing-application.md
  content/web/tutorials-bundle/remove-login-and-authentication.md
  content/web/tutorials-bundle/requesting-data-from-a-custom-microservice.md
  content/web/upgrade-bundle/update-to-an-newer-version.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.17.0

#1419 [MTM-55504][1016] add entry about custom web sdk registry
  content/web/development-tools-bundle/c8y-cli.md
  content/web/libraries.md
  content/web/tutorials-bundle/add-a-custom-widget.md
  content/web/tutorials-bundle/add-a-tab-to-a-device.md
  content/web/tutorials-bundle/add-a-unit-test.md
  content/web/tutorials-bundle/extend-an-existing-application.md
  content/web/tutorials-bundle/remove-login-and-authentication.md
  content/web/tutorials-bundle/requesting-data-from-a-custom-microservice.md
  content/web/upgrade-bundle/update-to-an-newer-version.md
Labels: documentation, auto-backport, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0

#1407 MTM-54143: reference-notifications2: type-filtering-changes-consistency and improve text on contexts and MO lifecycle event messages
  content/reference/notifications-bundle/overview.md
Labels: 10.16.0, 10.17.0, 10.18.0

#1436 [MTM-55028] Document that SSO in c8y does not support SAML based auth…
  content/users-guide/administration-bundle/configuring-single-sign-on.md
Labels: 10.15.0, 10.16.0, 10.17.0, 10.18.0
