Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-08, with the labels that each got.

#1275 Merge pull request #1228 from SoftwareAG/feature/MTM-53705/notification2-reference-improvements 1018
  content/reference/notifications-bundle/consumer-protocol.md
  content/reference/notifications-bundle/overview.md
  static/images/reference-guide/notification2/notification2-consumers.svg
  static/images/reference-guide/notification2/notification2-subscriptions.svg
  static/images/reference-guide/notification2/notifications2-backlog-lifecycle.svg
Labels: documentation

#1238 Update OEE to 10.17 and Shifts feature.
  content/oee/oee-administration-bundle/machine-profiles.md
  content/oee/oee-administration-bundle/organization.md
  content/oee/oee-administration-bundle/shiftplan.md
  content/oee/oee-dashboards-bundle/andon-board.md
  content/oee/oee-dashboards-bundle/machine-dashboard.md
  content/oee/oee-dashboards-bundle/machine-park.md
  content/oee/oee-faq-bundle/calculation.md
  content/oee/oee-faq-bundle/production-plan.md
  content/oee/oee-theory-bundle/splitting.md
  static/images/oee/administration/admin-create-site.png
  static/images/oee/administration/admin-organization.png
  static/images/oee/administration/admin-profile-settings.png
  static/images/oee/administration/admin-shift-plans.png
  static/images/oee/administration/example-matching.png
  static/images/oee/administration/line-profile-line.png
  static/images/oee/administration/machine-profile-machine.png
  static/images/oee/administration/mapping-view-for-splitting-1.png
  static/images/oee/administration/matching-events-with-path.png
  static/images/oee/administration/matching-general.png
  static/images/oee/administration/profile-computation.png
  static/images/oee/administration/profile-create.png
  static/images/oee/administration/profile-goals.png
  static/images/oee/administration/profile-resolution.png
  static/images/oee/administration/profile-shortstoppages.png
  static/images/oee/administration/profile-summary.png
  static/images/oee/administration/profile-workpiece.png
  static/images/oee/dashboards/dashboard-alarm-details.png
  static/images/oee/dashboards/dashboard-alarm-list.png
  static/images/oee/dashboards/dashboard-alarm-severity.png
  static/images/oee/dashboards/dashboard-andon-board.png
  static/images/oee/dashboards/dashboard-entity-details.png
  static/images/oee/dashboards/dashboard-export-csv-4-2.png
  static/images/oee/dashboards/dashboard-machine-dashboard.png
  static/images/oee/dashboards/dashboard-machine-park-overview.png
  static/images/oee/dashboards/dashboard-oee-status.png
  static/images/oee/dashboards/dashboard-section-view-chart-2.png
  static/images/oee/dashboards/dashboard-section-view-chart-3.png
  static/images/oee/dashboards/dashboard-section-view.png
  static/images/oee/dashboards/dashboard-shift-in-graph-1.png
  static/images/oee/dashboards/dashboard-shift-in-graph-2.png
  static/images/oee/dashboards/dashboard-single-view.png
  static/images/oee/faq/faq-actual-production-amount.png
  static/images/oee/faq/faq-actual-quality-amount.png
  static/images/oee/faq/faq-chart-loading-issue.png
  static/images/oee/faq/faq-dashboard-alarm.png
Labels: auto-backport, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#272 [MTM-36806] Introduced i18n tutorial to WebSdk guide
  content/web/tutorials-bundle/internationalization.md
Labels: 10.16.0

#1288 CIE-4835. Updated the VMware version numbers.
  content/edge/installation-bundle/prerequisites.md
Labels: auto-backport, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1293 web sdk tutorial language review addendum
  content/web/tutorials-bundle/internationalization.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1285 User guide update for Apama-ctrl
  content/users-guide/administration-bundle/managing-microservices.md
Labels: 10.17.0, auto-backport, auto-backport-to-release/r10.17.0, 10.18.0, auto-backport-to-release/r10.18.0, 10.19.0

#1286 Dm 2425 add documentation about validation configuration switch addition
  content/protocol-integration/opcua-bundle/rest-api.md
Labels: auto-backport, auto-backport-to-release/r10.18.0

#1304 [no-issue] add missing squared bracket in websdk tutorial
  content/web/tutorials-bundle/extend-an-existing-application.md
Labels: auto-backport, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0

#1308 added a deprecation note to the machine learning guide chapters
  content/machine-learning/activity-recognition.md
  content/machine-learning/anomaly-detection.md
  content/machine-learning/api-reference-mlw.md
  content/machine-learning/api-reference.md
  content/machine-learning/casting-defect-detection.md
  content/machine-learning/demand-forecasting.md
  content/machine-learning/machine-learning-introduction.md
  content/machine-learning/remaining-useful-life.md
  content/machine-learning/web-app-mlw.md
  content/machine-learning/web-app.md
  content/machine-learning/welding-defect-detection.md
Labels: 10.16.0, 10.17.0, auto-backport, auto-backport-to-release/r10.16.0

#1306 Platform administration
  content/authentication/basic-settings.md
  content/authentication/sso-bundle/azure.md
  content/authentication/sso-bundle/configuration.md
  content/authentication/sso-bundle/configuring-access-tokens.md
  content/authentication/sso-bundle/custom-template.md
  content/authentication/sso-bundle/keycloak.md
  content/authentication/sso-bundle/sso-introduction.md
  content/authentication/tfa-bundle/sms.md
  content/authentication/tfa-bundle/tfa-introduction.md
  content/authentication/tfa-bundle/totp.md
  content/data-broker/data-broker-bundle/data-connectors.md
  content/data-broker/data-broker-bundle/data-subscriptions.md
  content/data-broker/data-broker-bundle/troubleshooting.md
  content/data-broker/data-broker-bundle/using-data-broker.md
  content/data-broker/data-broker.md
  content/data-broker/ms-data-broker-bundle/ms-troubleshooting.md
  content/data-broker/ms-data-broker-bundle/using-ms-data-broker.md
  content/data-broker/ms-data-broker.md
  content/enterprise-tenant/customization-bundle/branding.md
  content/enterprise-tenant/customization-bundle/configuration.md
  content/enterprise-tenant/customization-bundle/domain-name.md
  content/enterprise-tenant/customization.md
  content/enterprise-tenant/license-management.md
  content/enterprise-tenant/support-user-access.md
  content/enterprise-tenant/tenant-management-bundle/custom-properties.md
  content/enterprise-tenant/tenant-management-bundle/default-subscriptions.md
  content/enterprise-tenant/tenant-management-bundle/managing-tenants.md
  content/enterprise-tenant/tenant-management-bundle/subscribing-applications.md
  content/enterprise-tenant/tenant-management-bundle/tenant-policies.md
  content/enterprise-tenant/tenant-management.md
  content/enterprise-tenant/timeseries.md
  content/enterprise-tenant/usage-and-billing.md
  content/enterprise-tenant/user-hierarchies.md
  content/standard-tenant/audit-logs.md
  content/standard-tenant/business-rules.md
  content/standard-tenant/changing-settings-bundle/application-settings.md
  content/standard-tenant/changing-settings-bundle/connectivity.md
  content/standard-tenant/changing-settings-bundle/properties.md
  content/standard-tenant/changing-settings-bundle/sms-provider.md
  content/standard-tenant/data-retention-bundle/files.md
  content/standard-tenant/data-retention-bundle/retention-rules.md
  content/standard-tenant/ecosystem-bundle/adding-applications.md
  content/standard-tenant/ecosystem-bundle/application-properties.md
  content/standard-tenant/ecosystem-bundle/archives.md
  content/standard-tenant/ecosystem-bundle/default-subscriptions.md
  content/standard-tenant/ecosystem-bundle/extensions.md
  content/standard-tenant/ecosystem-bundle/managing-applications.md
  content/standard-tenant/ecosystem-bundle/managing-microservices.md
  content/standard-tenant/ecosystem-bundle/monitoring-microservices.md
  content/standard-tenant/ecosystem.md
  content/standard-tenant/home-screen.md
  content/standard-tenant/managing-permissions-bundle/global-roles.md
  content/standard-tenant/managing-permissions-bundle/improving-performance.md
  content/standard-tenant/managing-permissions-bundle/inventory-roles.md
  content/standard-tenant/managing-permissions.md
  content/standard-tenant/managing-users.md
  content/tenant-management/custom-properties.md
  content/tenant-management/default-subscriptions.md
  content/tenant-management/subscribing-applications.md
  content/tenant-management/tenant-policies.md
Labels: Draft

#1311 New: Application solutions & enablement
  content/cockpit/cockpit-configuration.md
  content/cockpit/dashboards.md
  content/cockpit/data-explorer-bundle/changing-visualization.md
  content/cockpit/data-explorer-bundle/working-with-data-explorer.md
  content/cockpit/data-point-library.md
  content/cockpit/exports.md
  content/cockpit/managing-assets-bundle/asset-hierarchy.md
  content/cockpit/managing-assets-bundle/working-with-assets.md
  content/cockpit/overview.md
  content/cockpit/reports.md
  content/cockpit/smart-rules-collection.md
  content/cockpit/smart-rules.md
  content/cockpit/widgets-collection.md
  content/dtm/asset-hierarchy-bundle/creating-assets-bulk-import.md
  content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
  content/dtm/asset-hierarchy-bundle/overview.md
  content/dtm/asset-hierarchy-bundle/viewing-assets.md
  content/dtm/asset-types-bundle/asset-types.md
  content/dtm/asset-types-bundle/property-library.md
  content/dtm/dtm-introduction-bundle/concepts-guide.md
  content/dtm/dtm-introduction.md
  content/dtm/localization.md
  content/microservice-sdk.md
  content/microservice-sdk/concept-bundle/microservice-runtime.md
  content/microservice-sdk/concept-bundle/security.md
  content/microservice-sdk/concept.md
  content/microservice-sdk/cs-bundle/hello-world.md
  content/microservice-sdk/cs-bundle/overview.md
  content/microservice-sdk/cs.md
  content/microservice-sdk/http.md
  content/microservice-sdk/java-bundle/developing-microservice.md
  content/microservice-sdk/java-bundle/microservice-java.md
  content/microservice-sdk/java.md
  content/microservice-sdk/rest-bundle/microservice-development.md
  content/microservice-sdk/rest-bundle/overview.md
  content/microservice-sdk/rest.md
  content/oee/oee-administration-bundle/machine-profiles.md
  content/oee/oee-administration-bundle/organization.md
  content/oee/oee-administration-bundle/shiftplan.md
  content/oee/oee-dashboards-bundle/andon-board.md
  content/oee/oee-dashboards-bundle/machine-dashboard.md
  content/oee/oee-dashboards-bundle/machine-park.md
  content/web.md
  content/web/overview.md
  content/web/tutorials.md
Labels: Draft

#1339 10.18.0 - Content fix Streaming Analytics
  content/users-guide/cockpit-bundle/exports.md
Labels: 10.18.0, old structure

#1340 10.17.0 - Content fix Streaming Analytics
  content/users-guide/cockpit-bundle/exports.md
Labels: 10.17.0, old structure
