Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-10, with the labels that each got.

#1459 MTM-53127 Added icon selector info to the docs.
  content/cockpit/cockpit-configuration.md
  content/standard-tenant/ecosystem-bundle/application-properties.md
  content/standard-tenant/ecosystem-bundle/custom-applications.md
Labels: 10.19.0

#1463 MTM-53338 Improved first sentence for the data explorer help context.
  content/users-guide/cockpit-bundle/data-explorer.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.17.0

#1462 MTM-53338 Improved first sentence for the data explorer help context.
  content/cockpit/data-explorer-bundle/changing-visualization.md
  content/cockpit/data-explorer-bundle/working-with-data-explorer.md
Labels: 10.14.0, 10.15.0, 10.16.0, 10.17.0, 10.18.0, 10.19.0

#1443 MTM-55444: edge-databroker: add new uninstall steps file
  content/edge/databroker-bundle/databroker-edge-uninstall.md
  content/edge/databroker-bundle/index.html
  content/edge/databroker.md
Labels: 10.18.0

#1456 [MTM-55237] Export time ranges - LAST_24H, LAST_7DAYS, LAST_30DAYS
  content/cockpit/managing-exports.md
Labels: 10.19.0

#1489 Update configuring-security.md
  content/edge/configuration-bundle/configuring-security.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0

#1503 [no-issue] ensure opened PR will get preview link comment
  .github/workflows/pull-request.yml
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0

#1505 MTM-56132 Added auto-scroll info to the correct widget.
  content/users-guide/cockpit-bundle/widgets-collection.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.14.0, auto-backport-to-release/r10.17.0
