Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-01, with the labels that each got.

#716 MTM-49948: added note, that it is possible to confirm POP by support
  content/device-integration/mqtt-bundle/device-certificates.md
Labels: 10.16.0

#794 Administration home screen and user list page screenshots changed to one with new layout
  static/images/users-guide/Administration/admin-home.png
  static/images/users-guide/Administration/admin-users-list.png
Labels: 10.17.0

#799 restored a versioned datahub link
  content/datahub/working-with-datahub-bundle/querying-offloaded.md
Labels: 10.13.0, 10.14.0, 10.15.0, 10.16.0, 10.17.0

#800 MTM-49761 fixes Microservice Security troubleshooting
  content/microservice-sdk/java-bundle/developing-microservice.md
Labels: 10.17.0

#803 Bugherd/task #644 and task #645
  content/device-integration/mqtt-bundle/device-certificates.md
Labels: 10.13.0, 10.14.0, 10.15.0, 10.16.0, 10.17.0
