Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2023-11, with the labels that each got.

#1450 [DTM] Asset location
  content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
  content/dtm/asset-hierarchy-bundle/viewing-assets.md
  content/dtm/asset-types-bundle/asset-models.md
  content/dtm/asset-types-bundle/asset-properties.md
Labels: documentation

#1522 BH #744 Correct the name of a called method
  content/web/microfrontends-bundle/add-a-new-package-as-blueprint.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0

#1523 BH #761 Updated html widget example content
  content/users-guide/cockpit-bundle/widgets-collection.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.15.0, auto-backport-to-release/r10.17.0

#1543 DM-1849 Document new flags introduced for LWM2M to disable default behaviors
  content/protocol-integration/lwm2m-bundle/device-details.md
  content/protocol-integration/lwm2m-bundle/registering-lwm2m-devices.md
Labels: 10.19.0
