Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2024-02, with the labels that each got.

#1642 fix: [MTM-57411] Adding jpg as supported format for brand logos
  content/enterprise-tenant/customization-bundle/branding.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0, auto-backport-to-release/r10.18.0, auto-backport-to-release/y2024

#1655 fix/[MTM-57411 jpg added to branding [graft] [10.18.0]
  content/users-guide/enterprise-tenant-bundle/customization.md
Labels: auto-backport, auto-backport-to-release/r10.16.0, auto-backport-to-release/r10.17.0

#1572 cd-banner for 1018
  themes/c8ydocs/static/js/main.js
Labels: on hold, 10.18.0

#1634 MTM-57487-Unify-usage-of-select-vs-choose
  content/change-logs/analytics/apama-in-c8y-24-18-0-Selection-lists-for-template-parameters.md
  content/cockpit/managing-exports.md
  content/device-integration/integration-tutorials-bundle/thin-edge-raspberry-pi.md
  content/dtm/asset-types-bundle/asset-models.md
  content/microservice-sdk/http-bundle/node-js-microservice.md
  content/microservice-sdk/java-bundle/developing-microservice.md
  content/oee/oee-faq-bundle/calculation.md
  content/oee/oee-faq-bundle/dashboards.md
Labels: auto-backport, auto-backport-to-release/y2024

#1671 removed device integration tutorials
  content/device-integration/device-integration-thin-edge.md
  content/device-integration/integration-tutorials-bundle/index.html
  content/device-integration/integration-tutorials-bundle/thin-edge-raspberry-pi.md
  content/device-integration/integration-tutorials-bundle/thin-edge-revolution-pi.md
  content/device-integration/integration-tutorials-bundle/tutorials-introduction.md
  content/device-integration/integration-tutorials.md
Labels: auto-backport, auto-backport-to-release/y2024

#1673 PAM-34643: Changed c8y_hardware to c8y_Hardware
  content/streaming-analytics/epl-apps-bundle/builtin-actions.md
Labels: auto-backport, auto-backport-to-release/y2024

#1610 DTM-Documentation changes for complex property order in Subassets page.
  content/dtm/asset-hierarchy-bundle/creating-assets-ui.md
Labels: auto-backport-to-release/y2024

#1647 [DM-3035] Add a note on recommended event type for logfile events
  content/device-integration/fragment-library-bundle/logs.md
Labels: auto-backport, auto-backport-to-release/y2024

#1666 MTM-56417-doc-cleanup-managing-applications-doc
  content/standard-tenant/ecosystem-bundle/extensions.md
Labels: auto-backport, auto-backport-to-release/y2024

#1686 [MTM-53170] update gs related docs
  content/enterprise-tenant/managing-tenants-bundle/custom-properties.md
  content/get-familiar-with-the-ui/user-settings.md
Labels: auto-backport, auto-backport-to-release/y2024

#1716 PAB-4369 - 25.54.0: Change log for UBI 9 upgrade
  content/change-logs/analytics/apama-in-c8y-25-54-0-Upgrade-to-Red-Hat-UBI-9.md
Labels: not-yet-deployed, streaming-analytics

#1720 PAQ: Move Info admonition to EPL Apps section
  content/streaming-analytics/epl-apps.md
  content/streaming-analytics/overview-analytics-bundle/streaming-analytics.md
Labels: auto-backport, auto-backport-to-release/y2024

#1718 PAB-4375 - 25.52.0: Change log for new Copy command
  content/change-logs/analytics/apama-in-c8y-25-52-0-New-command-for-copying-the-JSON-code-of-a-model.md
Labels: not-yet-deployed, streaming-analytics

#1717 PAB-4376 - 25.55.0: Change log for new filters in device selection dialog
  content/change-logs/analytics/apama-in-c8y-25-55-0-New-filters-for-selecting-the-input-source-or-output-destination.md
Labels: not-yet-deployed, streaming-analytics

#1734 Create ui-c8y-1019-6-4-map-widget-in-dashboard-created-along-connecting-smartphone-has-no-device-assigned-5350-graft-release-cd-5591.md
  content/change-logs/ui-c8y-1019-6-4-map-widget-in-dashboard-created-along-connecting-smartphone-has-no-device-assigned-5350-graft-release-cd-5591.md
Labels: auto-backport, auto-backport-to-release/y2024

#1740 Create ui-c8y-1019-6-5-allowing-more-links-on-login-page-and-show-it-on-all-public-facing-pages-allows-to-add-more-than-one-link-on-the-login-page-those-links-are-shown-all-public-facing-pages-not-only-on-the-login-page.md
  content/change-logs/ui-c8y-1019-6-5-enabling-multiple-links-on-the-login-page-which-are-shown-on-all-public-facing-pages.md
Labels: auto-backport, auto-backport-to-release/y2024

#1728 Create ui-c8y-1019-6-3-3-d-rotation-model-shows-the-actual-model-5566.md
  content/change-logs/ui-c8y-1019-6-3-3-d-rotation-model-shows-the-actual-model-5566.md
Labels: auto-backport, auto-backport-to-release/y2024

#1752 PAB-4379: Internal error for inconsistent chain ID
  content/change-logs/analytics/apama-in-c8y-20240228-Asynchronous-alarm-inputs-no-longer-cause-internal-errors-in-model-chains.md
Labels: not-yet-deployed, streaming-analytics

#1684 PAQ 25.52.0 - New section "Copying a model" (PAB-3198 / PAB-4375)
  content/streaming-analytics/analytics-builder-bundle/using-the-model-manager.md
Labels: streaming-analytics

#1687 PAQ 25.55.0 - New filters in device selection dialog ( PAB-4308 / PAB-4376 )
  content/streaming-analytics/analytics-builder-bundle/models-and-devices.md
  content/streaming-analytics/analytics-builder-bundle/monitoring-and-configuration.md
  content/streaming-analytics/analytics-builder-bundle/using-the-model-editor.md
Labels: streaming-analytics
