Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2025-02, with the labels that each got.

#2859 [2025] PAB-4691 - Change log entry for duplicate alarms with geofence smart rule
  content/change-logs/analytics/apama-in-c8y-20250128-The-Smartrule-service-will-now-disregard-rule-edits-unless-there-is-a-configuration-change.md
Labels: streaming-analytics

#2884 [2025] PAB-4691 - Add changelog date for smartrules fix
  content/change-logs/analytics/apama-in-c8y-20250128-The-Smartrule-service-will-now-disregard-rule-edits-unless-there-is-a-configuration-change.md
Labels: streaming-analytics

#2670 PAB-4575: New template parameter field for source or destination type in Analytics Builder
  content/change-logs/analytics/apama-in-c8y-20241122-New-template-parameter-field-in-Analytics-Builder-to-select-source-or-destination type.md
  content/streaming-analytics/analytics-builder-bundle/using-the-model-editor.md
Labels: streaming-analytics

#2888 MTM-62347: Fixed NullPointerException when user was queries Measureme…
  content/change-logs/platform-services/cumulocity-2025.44.0-fix-NPE-when-query-measurement-API-using-valueSeriesFragment-with-inventory-roles-permissions.md
Labels: auto-backport, auto-backport-to-release/y2024, release/y2024, auto-backport-to-release/y2025

#2896 [EDGE] y2024 release notes updates
  content/change-logs/edge/edge-appliance-vm-10-18-0-0-Deprecation-of-cumulocity-linux-agent-included-in-the-cumulocity-edge.md
  content/change-logs/edge/edge-appliance-vm-10-18-0-0.md
  content/change-logs/edge/edge-appliance-vm-10-18-0-1-Diagnostic-utility-no-longer-generates-excessive-logs.md
  content/change-logs/edge/edge-appliance-vm-10-18-0-1-Fixed-cumulocity-agent-crashing-when-registering-a-child-device.md
  content/change-logs/edge/edge-appliance-vm-10-18-0-1-Temporary-directory-used-by-core-is-monitored-and-recreated-if-necessary.md
  content/change-logs/edge/edge-appliance-vm-10-18-0-1-Upgrade-Rocky-to-8-10.md
  content/change-logs/edge/edge-appliance-vm-10-18-0-Release-identical-to-10-18.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-0-Metrics-monitoring.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-0-Offline-installation.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-0-Remote-software-management.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-0.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-1-Metrics-monitoring-port.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-1-Offline-installation.md
  content/change-logs/edge/edge-on-kubernetes-10-18-0-Release-identical-to-10-18.md
  content/edge-kubernetes/k8-connecting-devices-to-edge-bundle/connecting-devices.md
  data/buildartifact.json
  data/component.json
  data/date_settings.toml
Labels: release/y2024, Edge

#2906 [EDGE] Added version shortcodes for c8y-edge major, minor, fix and full.
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-specification.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/install-edge.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/install-operator-offline.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/install-operator.md
  content/edge-kubernetes/k8-edge-introduction-bundle/versions.md
  content/edge-kubernetes/k8s-troubleshooting-bundle/edge-k8s-cr-status-install-update-loop-backoff.md
  content/edge-kubernetes/k8s-troubleshooting-bundle/edge-k8s-does-not-show-as-device-on-cloud.md
  content/edge-kubernetes/manage-edge-bundle/version-upgrade.md
  content/edge-kubernetes/quickstart.md
  themes/c8ydocs/layouts/shortcodes/c8y-edge-version-major.html
  themes/c8ydocs/layouts/shortcodes/c8y-edge-version-minor.html
  themes/c8ydocs/layouts/shortcodes/c8y-edge-version-patch.html
  themes/c8ydocs/layouts/shortcodes/c8y-edge-version.html
Labels: Draft, Edge

#2860 Apama current upgrades and future deprecation announcements
  content/change-logs/analytics/apama-in-c8y-20250129-Upgrade-of-python-java-and-Depreication-of-Support-for-Eclipse-in-Apama.md
Labels: streaming-analytics

#2919 MTM-62228 Clean up user documentation for the data broker microservice
  content/data-broker/ms-data-broker-bundle/ms-troubleshooting.md
  content/data-broker/ms-data-broker-bundle/using-ms-data-broker.md
Labels: auto-backport-to-release/y2025

#2881 MTM-61873 - release notes - alarm/count returns 0 when more than one type specified
  content/change-logs/platform-services/cumulocity-20-25-37-0_alarm-collection-count-single-type-fix.md
Labels: auto-backport-to-release/y2024, auto-backport-to-release/y2025

#2947 MTM-62693 removing the extra comma from an invalid JSON
  content/standard-tenant/managing-data-bundle/latest-value.md
Labels: auto-backport, auto-backport-to-release/y2024, auto-backport-to-release/y2025

#2951 Fix broken link for apama prometheus documentation
  content/streaming-analytics/troubleshooting-bundle/diagnostics-rest.md
  content/streaming-analytics/troubleshooting-bundle/monitoring-rest.md
Labels: auto-backport, auto-backport-to-release/y2024, streaming-analytics, auto-backport-to-release/y2025

#2933 [L2S-405] adapt docu for microservice production versioning
  content/microservice-sdk/general-aspects-bundle/microservice-manifest.md
Labels: auto-backport-to-release/y2024, auto-backport-to-release/y2025

#2965 MTM-62312: Fix failure of tenant creation with tenant policy that contains override of default tenant option
  content/change-logs/platform-services/cumulocity-2025.72.0-fix-failure-when-tenant-with-tenant-policy.md
Labels: auto-backport-to-release/y2024, auto-backport-to-release/y2025

#2634 merged introduction from concepts section into microservices SDK section
  content/concepts/applications-bundle/microservices.md
  content/concepts/applications.md
  content/microservice-sdk/general-aspects-bundle/introduction.md
Labels: on hold

#2946 announcement: [DM-4367] Removed obsolete AngularJS implementation of cloud remote access feature
  content/change-logs/device-management/ui-c8y-1022-0-0-removed-obsolete-angularjs-implementation-of-cloud-remote-access.md
Labels: not-yet-deployed

#2994 Change log/ 4026/lwm2m improved decoder execution
  content/change-logs/device-management/lwm2m-agent-1020-440-9-optimization-and-improvement-of-the-lwm-2-m-decoder-events-processing.md
Labels: DM-docs
