Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2025-04, with the labels that each got.

#3143 [DM-4470] Admin permissions added to the Loriot agent output user for existing and new devices
  content/change-logs/device-management/loriot-3-0-18-operation-processing-stops-when-error-occurs.md
Labels: DM-docs, DM-backend

#3136 [DM-4487] - lwm2m change log
  content/change-logs/device-management/cumulocity-10-18-540-287-lwm2m-lazy-migration-fix.md
Labels: DM-docs

#3179 DM-4555: Simplifying log event levels
  content/device-integration/lwm2m-bundle/device-details.md
  content/device-integration/lwm2m-bundle/registering-lwm2m-devices.md
Labels: DM-docs

#3142 [L2S-471] Documentation of the microservice-package-maven-plugin parameter specification
  content/microservice-sdk/java-bundle/developing-microservice.md
Labels: auto-backport, auto-backport-to-release/y2024, auto-backport-to-release/y2025

#3200 Clarify measurement documentation for better understanding of value a…
  content/concepts/domain-model-bundle/measurements.md
Labels: auto-backport, auto-backport-to-release/y2025

#3128 DM-4543 As device integrator I want documentation on how to create child device
  content/device-integration/fragment-library-bundle/child-devices.md
  content/device-integration/fragment-library-bundle/device-info.md
  content/smartrest/mqtt-static-templates.md
Labels: DM-docs

#3131 [EDGE CIE-5221] y2025 DataHub installation using the Edge Operator
  content/change-logs/edge/edge-on-kubernetes-2025.0.0-datahub.md
  content/change-logs/edge/edge-on-kubernetes-2025.0.0-messaging-service.md
  content/datahub/running-datahub-on-the-edge-bundle/datahub-edge-overview.md
  content/datahub/running-datahub-on-the-edge-bundle/operating-datahub-edge.md
  content/datahub/running-datahub-on-the-edge-bundle/setting-up-datahub-edge-on-k8s.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-cloud-tenant.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-configuration.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-datahub.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-dremio-cred-secret.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-microservices.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-mongodb-cred-secret.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-mongodb.md
  content/edge-kubernetes/edge-custom-resource-definition-bundle/k8-edge-specification.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/configuring-storage.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/prerequisites.md
  content/edge-kubernetes/k8-edge-connecting-edge-to-cloud-bundle/k8-edge-register-edge-on-cloud.md
  content/edge-kubernetes/k8-edge-working-with-datahub-bundle/datahub-edge.md
  content/edge-kubernetes/k8s-edge-messaging-service.md
  content/edge/edge-introduction-bundle/overview.md
  content/edge/edge-update-bundle/migration-1017-to-1018.md
  content/edge/edge-working-with-datahub-bundle/datahub-edge-overview.md
  content/edge/edge-working-with-datahub-bundle/datahub-edge.md
  content/edge/edge-working-with-datahub-bundle/index.html
  content/edge/edge-working-with-datahub-bundle/operating-datahub-edge.md
  content/edge/edge-working-with-datahub-bundle/setting-up-datahub-edge.md
  content/edge/edge-working-with-datahub-bundle/working-with-datahub-edge.md
  content/edge/edge-working-with-datahub.md
  content/edge/operating-edge-bundle/logs-files.md
  static/files/edge-k8s/c8yedge-pv-local-path.yaml
  static/files/edge-k8s/c8yedge-pv-nfs.yaml
  static/files/edge-k8s/c8yedge.yaml
Labels: Edge

#3229 [EDGE] CIE-5382 Correct operator clusterrole patch command
  content/edge-kubernetes/manage-edge-bundle/version-upgrade.md
Labels: Edge

#3231 Cumulocity logo no longer appears when custom branding is applied[PAB-4764]
  content/change-logs/analytics/apama-in-c8y-24-41-41-c8y-logo-no-longer-appears-when-custom-branding-is-applied.md
Labels: streaming-analytics

#3252 remove HDFS from Datahub
  content/datahub/datahub-overview-bundle/datahub-at-a-glance.md
  content/datahub/running-datahub-on-the-edge-bundle/datahub-edge-overview.md
  content/datahub/setting-up-datahub-bundle/setting-up-initial-configuration.md
  content/glossary/d.md
Labels: auto-backport, auto-backport-to-release/y2024, auto-backport-to-release/y2025

#3201 Clarify subtenant suspension process and data retention details in do…
  content/enterprise-tenant/managing-tenants-bundle/managing-subtenants.md
Labels: auto-backport, auto-backport-to-release/y2025

#3251 correct bullet alignment
  content/smartrest/mqtt-static-templates.md
Labels: auto-backport, auto-backport-to-release/y2025

#3122 [DM-2354] - updated description of lwm2m request timeout
  content/device-integration/lwm2m-bundle/registering-lwm2m-devices.md
Labels: DM-docs

#3197 Added change log for Dropping native windows support
  content/change-logs/analytics/apama-in-c8y-25-56-0-Remove-windows-support.md
Labels: not-yet-deployed
