Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2025-05, with the labels that each got.

#3275 [EDGE CIE-4954] Edge on K8s updated supported kubernetes versions
  content/change-logs/edge/edge-on-kubernetes-2025.0.1-supported-kubernetes-versions.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/install-operator-offline.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/install-operator.md
  content/edge-kubernetes/installing-edge-on-k8-bundle/prerequisites.md
  content/edge-kubernetes/manage-edge-bundle/version-upgrade.md
  content/edge-kubernetes/quickstart.md
Labels: Edge

#3307 change log: discarded equals
  content/change-logs/analytics/apama-in-c8y-26-105-0-discarded-equals-is-error.md
Labels: streaming-analytics

#3309 [MTM-63365] Adapted documentation for better readibility and understanding
  content/microservice-sdk/general-aspects-bundle/microservice-manifest.md
  content/microservice-sdk/java-bundle/developing-microservice.md
Labels: auto-backport, auto-backport-to-release/y2024, auto-backport-to-release/y2025

#3293 [DM-4560] resolve two resource instance related issues
  content/change-logs/device-management/lwm2m-agent-1021-10-7-resolve-two-resource-instance-issues.md
Labels: DM-docs

#3313 [MTM-63219] Docu was updated to the new spring boot version 3.4.5
  content/microservice-sdk/java-bundle/ip-tracker-microservice.md
  content/microservice-sdk/java-bundle/java-hello-world-tutorial.md
Labels: auto-backport, auto-backport-to-release/y2025
