Repository Cumulocity-IoT/c8y-docs, pull requests merged in 2025-03, with the labels that each got.

#2967 Enhanced documentation in time series section with feedback from support
  content/standard-tenant/enhanced-time-series-support-bundle/general-configuration.md
  content/standard-tenant/enhanced-time-series-support-bundle/migration-process-description.md
Labels: auto-backport, auto-backport-to-release/y2025

#3014 Improve documentation for streaming analytics feature application toggle
  content/streaming-analytics/analytics-customization-bundle/control-access.md
Labels: auto-backport, auto-backport-to-release/y2024, auto-backport-to-release/y2025

#3007 DM-4488 Home dashboard screen retaken manually
  static/images/users-guide/DeviceManagement/device-management-home-screen.png
Labels: DM-docs

#3033 DM-4497 SmartREST Screenshots Branding change
  static/images/users-guide/DeviceManagement/devmgmt-devicetypes-smartrest-addmessage.png
  static/images/users-guide/DeviceManagement/devmgmt-devicetypes-smartrest-addresponse.png
  static/images/users-guide/DeviceManagement/devmgmt-devicetypes-smartrest.png
Labels: DM-docs

#3009 [DM-4343] - updated screenshots for lwm2m and opcua documentation
  static/images/device-protocols/lwm2m/lwm2m-autoobserve.png
  static/images/device-protocols/lwm2m/lwm2m-connector-device-bulk-device-reg-res.png
  static/images/device-protocols/lwm2m/lwm2m-custom-action-connectivity-signal.png
  static/images/device-protocols/lwm2m/lwm2m-deviceprotocol.png
  static/images/device-protocols/lwm2m/lwm2m-devices-operations.png
  static/images/device-protocols/lwm2m/lwm2m-objects.png
  static/images/device-protocols/lwm2m/lwm2m-post-operations.png
  static/images/device-protocols/lwm2m/lwm2m-protocol-example.png
  static/images/device-protocols/lwm2m/lwm2m-protocols-example-validation.png
  static/images/device-protocols/lwm2m/lwm2m-protocols-rules.png
  static/images/device-protocols/opcua/opcua-add-protocol.png
  static/images/device-protocols/opcua/opcua-address.png
  static/images/device-protocols/opcua/opcua-alarms.png
  static/images/device-protocols/opcua/opcua-auto-constraints.png
  static/images/device-protocols/opcua/opcua-data-reporting-subscription.png
  static/images/device-protocols/opcua/opcua-device-details.png
  static/images/device-protocols/opcua/opcua-device-protocol-applied.png
  static/images/device-protocols/opcua/opcua-device-protocol-unapplied.png
  static/images/device-protocols/opcua/opcua-device-protocol.png
  static/images/device-protocols/opcua/opcua-device-registration-gateway.png
  static/images/device-protocols/opcua/opcua-device-registration.png
  static/images/device-protocols/opcua/opcua-events.png
  static/images/device-protocols/opcua/opcua-gateway-memory.png
  static/images/device-protocols/opcua/opcua-keystore.png
  static/images/device-protocols/opcua/opcua-new-server.png
  static/images/device-protocols/opcua/opcua-server-child-device.png
Labels: DM-docs

#3002 [DM-4495] Replace screenshots for managing device types
  static/images/users-guide/DeviceManagement/devmgmt-device-protocols.png
Labels: DM-docs

#2997 [DM-4489] Replace screenshots for registering devices
  static/images/concepts-guide/extensible-device-registration/extensible-bulk-device-reg.png
  static/images/concepts-guide/extensible-device-registration/extensible-single-device-reg.png
  static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-ignored-security.png
  static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security-enter-token.png
  static/images/users-guide/DeviceManagement/devmgmt-at-register-device-pending-acceptance-optional-security.png
  static/images/users-guide/DeviceManagement/devmgmt-device-registration-tenant.png
  static/images/users-guide/DeviceManagement/devmgmt-device-registration.png
Labels: DM-docs

#3028 [DM-4499] replace screenshots for connectivity
  content/device-management-application/connectivity.md
  static/images/users-guide/connectivity/connectivity-item.png
  static/images/users-guide/connectivity/connectivity-permissions.png
  static/images/users-guide/connectivity/connectivity-tab.png
Labels: DM-docs

#3036 Automated Handover: 24.41.30 Analytics Builder Block Reference Documentation.
  content/streaming-analytics/block-reference-bundle/aggregate.md
  content/streaming-analytics/block-reference-bundle/calculation.md
  content/streaming-analytics/block-reference-bundle/utility.md
Labels: streaming-analytics

#3038 L2S-332: document inventory roles limits
  content/standard-tenant/managing-permissions-bundle/limititations.md
Labels: auto-backport, auto-backport-to-release/y2025

#3043 DM-4504 Sigfox image changes
  static/images/device-protocols/sigfox/sigfox-admin-settings-delete.png
  static/images/device-protocols/sigfox/sigfox-bits.png
  static/images/device-protocols/sigfox/sigfox-connectivity-update.png
  static/images/device-protocols/sigfox/sigfox-protocol.png
Labels: DM-docs

#3029 DM-4492: viewing device details screenshots
  static/images/users-guide/DeviceManagement/devmgmt-devices-control.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-info.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-infotab.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-location.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-logs.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-measurements.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-more.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-network.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-shell.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-textconfig.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-tracking.png
  static/images/users-guide/DeviceManagement/devmgmt-services-overview.png
Labels: DM-docs

#3049 [DM-4344] - updated screenshots for managing device data part
  static/images/users-guide/DeviceManagement/devmgmt-crl-offline-option-check.png
  static/images/users-guide/DeviceManagement/devmgmt-crl-online-option-check.png
  static/images/users-guide/DeviceManagement/devmgmt-device-credentials-details.png
  static/images/users-guide/DeviceManagement/devmgmt-device-credentials.png
  static/images/users-guide/DeviceManagement/devmgmt-device-profile-details.png
  static/images/users-guide/DeviceManagement/devmgmt-device-profile-list.png
  static/images/users-guide/DeviceManagement/devmgmt-device-profile-tab.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-config-getnewsnapshot.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-config-old-getnewsnapshot.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-config-putsnapshot.png
  static/images/users-guide/DeviceManagement/devmgmt-devices-config-text-getnewsnapshot.png
  static/images/users-guide/DeviceManagement/devmgmt-firmware-add.png
  static/images/users-guide/DeviceManagement/devmgmt-firmware-details.png
  static/images/users-guide/DeviceManagement/devmgmt-firmware-list.png
  static/images/users-guide/DeviceManagement/devmgmt-firmware-tab.png
  static/images/users-guide/DeviceManagement/devmgmt-management-configrepo.png
  static/images/users-guide/DeviceManagement/devmgmt-management-configrepoedit.png
  static/images/users-guide/DeviceManagement/devmgmt-management-menu.png
  static/images/users-guide/DeviceManagement/devmgmt-software-add.png
  static/images/users-guide/DeviceManagement/devmgmt-software-details.png
  static/images/users-guide/DeviceManagement/devmgmt-software-repository.png
  static/images/users-guide/DeviceManagement/devmgmt-software-tab.png
  static/images/users-guide/DeviceManagement/devmgmt-trusted-certificates-details.png
  static/images/users-guide/DeviceManagement/devmgmt-trusted-certificates-list.png
Labels: DM-docs

#3051 [DM-4501] [Protocol integration] Actility LoRa
  static/images/device-protocols/lora-actility/lora-admin-settings-delete.png
  static/images/device-protocols/lora-actility/lora-admin-settings-update.png
  static/images/device-protocols/lora-actility/lora-admin-settings.png
  static/images/device-protocols/lora-actility/lora-devices-deprovision.png
  static/images/device-protocols/lora-actility/lora-devices-port.png
  static/images/device-protocols/lora-actility/lora-lpwan-tab.png
  static/images/device-protocols/lora-actility/lora-registration-no-credentials.png
  static/images/device-protocols/lora-actility/lora-registration-no-devicetype.png
  static/images/device-protocols/lora-actility/lora-registration.png
  static/images/device-protocols/lora-actility/lora-selection.png
Labels: DM-docs, DM-backend

#3032 [DM-4500] [Protocol integration] Loriot LoRa screenshots
  static/images/device-protocols/lora-actility/lora-protocols-addvalue.png
  static/images/device-protocols/lora-actility/lora-protocols-battery.png
  static/images/device-protocols/lora-actility/lora-protocols-battery2.png
  static/images/device-protocols/lora-actility/lora-protocols-gpsexample.png
  static/images/device-protocols/lora-actility/lora-protocols-import.png
  static/images/device-protocols/lora-actility/lora-protocols-lat.png
  static/images/device-protocols/lora-actility/lora-protocols-lng.png
  static/images/device-protocols/lora-actility/lora-protocols-lorabits.png
  static/images/device-protocols/lora-actility/lora-protocols-loraid.png
  static/images/device-protocols/lora-actility/lora-protocols-loraprotocol.png
  static/images/device-protocols/lora-actility/lora-protocols-new.png
  static/images/device-protocols/lora-actility/lora-protocols-newvalue.png
  static/images/device-protocols/lora-actility/lora-protocols-newvalue2.png
  static/images/device-protocols/lora-actility/lora-protocols-payload.png
  static/images/device-protocols/lora-loriot/loriot-admin-settings-delete.png
  static/images/device-protocols/lora-loriot/loriot-admin-settings-update.png
  static/images/device-protocols/lora-loriot/loriot-device-protocol-assignment.png
  static/images/device-protocols/lora-loriot/loriot-devices-port.png
  static/images/device-protocols/lora-loriot/loriot-devices-predefinedshell.png
  static/images/device-protocols/lora-loriot/loriot-registration.png
  static/images/device-protocols/lora-loriot/loriot-selection.png
  static/images/device-protocols/lora-loriot/loriot-user-admin-role.png
Labels: DM-docs, DM-backend

#3022 [DM-4491] [DM application] Grouping devices screenshots
  static/images/users-guide/DeviceManagement/devmgmt-group-assign.png
  static/images/users-guide/DeviceManagement/devmgmt-group-details.png
  static/images/users-guide/DeviceManagement/devmgmt-groups-smartgroups-filter.png
  static/images/users-guide/DeviceManagement/devmgmt-groups.png
Labels: DM-docs, DM-backend

#2865 Create ui-c8y-1021-34-2-ui-make-device-info-delete-button-use-lwm-2-m-agent.md
  content/change-logs/device-management/ui-c8y-1021-34-2-ui-make-device-info-button-use-lwm-2-m-agent.md
  content/device-integration/lwm2m-bundle/registering-lwm2m-devices.md
Labels: DM-docs

#3073 DM-4363 - lwm2m agent changelog
  content/change-logs/device-management/lwm2m-agent-1020-440-11-fixed-a-rare-condition-where-already-expired-realtime-subscription-was-still.md
Labels: DM-docs

#3076 DM-4423 - lwm2m agent changelog
  content/change-logs/device-management/lwm2m-agent-1020-440-13-fixed-lwm-2-m-event-processing-failed-issue-when-external-decoder.md
Labels: DM-docs

#3064 DM-4503 Update screenshots for cloud fieldbus
  static/images/device-protocols/cloud-fieldbus/fieldbus-category.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-deviceprotocols-modbus.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-deviceprotocols-newcoil.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-deviceprotocols-newregister.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-export-protocol.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-modbus-alarms.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-modbus-events-log.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-modbus-measurements.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-modbus-rtu.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-modbus-status.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-modbus-tcp.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-new-can-device.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-new-profibus.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-new-variable.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-scada-edit.png
  static/images/device-protocols/cloud-fieldbus/fieldbus-widget.png
Labels: DM-docs

#3077 DM-4363 - lwm2m agent changelog
  content/change-logs/device-management/cumulocity-10-18-540-286-lwm2m-agent-expiring-map-fix.md
Labels: DM-docs

#3063 Announcement for removing LWM2M Module from ngx-components
  content/change-logs/application-enablement/ui-c8y-1022-0-0-remove-lwm2m-module-from-ngx-components.md
Labels: not-yet-deployed

#3097 MTM-63002: databroker: remove unnecessary databroker alarm images
  content/data-broker/data-broker-application-bundle/data-broker-troubleshooting.md
  content/data-broker/ms-data-broker-bundle/ms-troubleshooting.md
  static/images/users-guide/enterprise-tenant/et-data-broker-alarm.png
  static/images/users-guide/enterprise-tenant/et-new-data-broker-alarms.png
Labels: documentation, auto-backport, auto-backport-to-release/y2025

#3113 DM-4504 Sigfox change leftover screenshots
  static/images/device-protocols/sigfox/sigfox-lpwan-tab.png
  static/images/device-protocols/sigfox/sigfox-newprotocol.png
  static/images/device-protocols/sigfox/sigfox-protocols-battery.png
  static/images/device-protocols/sigfox/sigfox-protocols-battery2.png
  static/images/device-protocols/sigfox/sigfox-protocols-gpsexample.png
  static/images/device-protocols/sigfox/sigfox-protocols-lat.png
  static/images/device-protocols/sigfox/sigfox-protocols-lng.png
  static/images/device-protocols/sigfox/sigfox-protocols-newvalue.png
  static/images/device-protocols/sigfox/sigfox-protocols-newvalue2.png
  static/images/device-protocols/sigfox/sigfox-protocols-sigfoxbits.png
  static/images/device-protocols/sigfox/sigfox-protocols-sigfoxid.png
  static/images/device-protocols/sigfox/sigfox-registration.png
  static/images/device-protocols/sigfox/sigfox-registration1.png
  static/images/device-protocols/sigfox/sigfox-troubleshooting-callback-typeid.png
  static/images/device-protocols/sigfox/sigfox-troubleshooting-callback.png
  static/images/device-protocols/sigfox/sigfox-troubleshooting-device-type-error.png
  static/images/device-protocols/sigfox/sigfox-troubleshooting-failedoperation.png
  static/images/device-protocols/sigfox/sigfox-troubleshooting-falseprovision.png
  static/images/device-protocols/sigfox/sigfox-troubleshooting-registration.png
Labels: DM-docs

#3124 MTM-62950 - release notes - Binary Search returns wrong results
  content/change-logs/platform-services/cumulocity-20-25-100-0-binaries-api-ids-filter-fix.md
Labels: auto-backport-to-release/y2025

#3135 MTM-63065 add announcement for timeseries migration introduction
  content/change-logs/platform-services/ts-migration-1-0-326-time-series-migration-introduction.md
  content/standard-tenant/ecosystem-bundle/subscribed-applications.md
Labels: auto-backport, auto-backport-to-release/y2025
